.data
.balign 8
donna_nil:
	.quad 0
/* end data */

.data
.balign 8
str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
str112:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str164:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str165:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str178:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
str181:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str183:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str186:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str188:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str191:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str198:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str201:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str209:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str222:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 16
.globl builder_lock_LockedDep
builder_lock_LockedDep:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x2
	mov	x20, x1
	mov	x19, x0
	mov	x0, #32
	bl	malloc
	mov	x2, x21
	mov	x1, x20
	mov	x3, #0
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x19, [x3]
	mov	x3, #16
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #24
	add	x1, x0, x1
	str	x2, [x1]
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_LockedDep, @function
.size builder_lock_LockedDep, .-builder_lock_LockedDep
/* end function builder_lock_LockedDep */

.text
.balign 16
.globl builder_lock_locked_name
builder_lock_locked_name:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_name, @function
.size builder_lock_locked_name, .-builder_lock_locked_name
/* end function builder_lock_locked_name */

.text
.balign 16
.globl builder_lock_locked_git
builder_lock_locked_git:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #16
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_git, @function
.size builder_lock_locked_git, .-builder_lock_locked_git
/* end function builder_lock_locked_git */

.text
.balign 16
.globl builder_lock_locked_rev
builder_lock_locked_rev:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #24
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_rev, @function
.size builder_lock_locked_rev, .-builder_lock_locked_rev
/* end function builder_lock_locked_rev */

.text
.balign 16
.globl builder_lock_read
builder_lock_read:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x19, x0
	bl	donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	.L21
	bl	donna_files_read
	bl	parsetoml_parsetoml_parse
	mov	x19, x0
	bl	parsetoml_parsetoml_is_err
	mov	x1, x0
	mov	x0, x19
	mov	x2, #16
	sub	sp, sp, x2
	mov	x19, sp
	cmp	x1, #1
	beq	.L19
	bl	parsetoml_parsetoml_unwrap_table
	adrp	x1, str46
	add	x1, x1, #:lo12:str46
	bl	parsetoml_parsetoml_get_table
	mov	x1, #16
	sub	sp, sp, x1
	mov	x20, sp
	ldr	x1, [x0]
	cmp	x1, #1
	beq	.L16
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	mov	x1, #16
	sub	sp, sp, x1
	mov	x21, sp
	ldr	x1, [x0]
	cmp	x1, #4
	beq	.L14
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x21]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	b	.L15
.L14:
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, donna_nil
	add	x1, x1, #:lo12:donna_nil
	bl	builder_lock_collect_locked
	str	x0, [x21]
.L15:
	str	x0, [x20]
	b	.L18
.L16:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x20]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
.L18:
	str	x0, [x19]
	b	.L22
.L19:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x19]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	b	.L22
.L21:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
.L22:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_read, @function
.size builder_lock_read, .-builder_lock_read
/* end function builder_lock_read */

.text
.balign 16
builder_lock_collect_locked:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	str	x24, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L28
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x21, [x1]
	ldr	x19, [x0]
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, str86
	add	x1, x1, #:lo12:str86
	mov	x22, x0
	bl	builder_lock_opt_str
	mov	x1, x0
	mov	x0, x22
	mov	x23, x1
	adrp	x1, str88
	add	x1, x1, #:lo12:str88
	bl	builder_lock_opt_str
	mov	x24, x0
	mov	x0, x19
	mov	x19, x0
	mov	x0, x23
	bl	donna_string_is_empty
	mov	x17, x0
	mov	x0, x19
	mov	x19, x17
	mov	x22, x0
	mov	x0, x24
	bl	donna_string_is_empty
	mov	x2, x24
	mov	x1, x23
	mov	x3, x0
	mov	x0, x22
	orr	x3, x19, x3
	mov	x4, #16
	sub	sp, sp, x4
	mov	x19, sp
	cmp	x3, #1
	beq	.L26
	bl	builder_lock_LockedDep
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x22, x0
	mov	x0, #24
	bl	malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	builder_lock_collect_locked
	str	x0, [x19]
	b	.L30
.L26:
	mov	x0, x21
	mov	x1, x20
	bl	builder_lock_collect_locked
	str	x0, [x19]
	b	.L30
.L28:
	mov	x0, x20
	bl	donna_list_reverse
.L30:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	ldr	x24, [x29, 16]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
.type builder_lock_collect_locked, @function
.size builder_lock_collect_locked, .-builder_lock_collect_locked
/* end function builder_lock_collect_locked */

.text
.balign 16
.globl builder_lock_find_rev
builder_lock_find_rev:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x1
	mov	x1, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L36
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x20, [x1]
	mov	x19, x0
	bl	builder_lock_locked_name
	mov	x1, x21
	mov	x21, x1
	bl	donna_string_equal
	mov	x1, x21
	mov	x2, x0
	mov	x0, x19
	mov	x3, #16
	sub	sp, sp, x3
	mov	x19, sp
	cmp	x2, #1
	beq	.L35
	mov	x0, x20
	bl	builder_lock_find_rev
	str	x0, [x19]
	b	.L37
.L35:
	bl	builder_lock_locked_rev
	str	x0, [x19]
	b	.L37
.L36:
	adrp	x0, str112
	add	x0, x0, #:lo12:str112
.L37:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_find_rev, @function
.size builder_lock_find_rev, .-builder_lock_find_rev
/* end function builder_lock_find_rev */

.text
.balign 16
.globl builder_lock_upsert
builder_lock_upsert:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x2, donna_nil
	add	x2, x2, #:lo12:donna_nil
	bl	builder_lock_upsert_loop
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_upsert, @function
.size builder_lock_upsert, .-builder_lock_upsert
/* end function builder_lock_upsert */

.text
.balign 16
builder_lock_upsert_loop:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	ldr	x3, [x0]
	cmp	x3, #0
	beq	.L45
	mov	x21, x2
	mov	x2, #8
	add	x2, x0, x2
	ldr	x22, [x2]
	mov	x19, x1
	mov	x1, #16
	add	x0, x0, x1
	ldr	x20, [x0]
	mov	x0, x22
	bl	builder_lock_locked_name
	mov	x23, x0
	mov	x0, x19
	bl	builder_lock_locked_name
	mov	x1, x0
	mov	x0, x23
	bl	donna_string_equal
	mov	x1, x19
	mov	x23, x1
	mov	x1, #16
	sub	sp, sp, x1
	mov	x19, sp
	cmp	x0, #1
	beq	.L43
	mov	x0, #24
	bl	malloc
	mov	x1, x23
	mov	x2, x0
	mov	x0, #1
	str	x0, [x2]
	mov	x0, #8
	add	x0, x2, x0
	str	x22, [x0]
	mov	x0, #16
	add	x0, x2, x0
	str	x21, [x0]
	mov	x21, x1
	mov	x0, x20
	bl	builder_lock_upsert_loop
	str	x0, [x19]
	b	.L47
.L43:
	mov	x2, x21
	mov	x21, x23
	mov	x0, x2
	bl	donna_list_reverse
	mov	x22, x0
	mov	x0, #24
	bl	malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	donna_list_append
	str	x0, [x19]
	b	.L47
.L45:
	mov	x20, x2
	mov	x19, x1
	mov	x0, #24
	bl	malloc
	mov	x2, x20
	mov	x1, x19
	mov	x3, #1
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #16
	add	x1, x0, x1
	str	x2, [x1]
	bl	donna_list_reverse
.L47:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
.type builder_lock_upsert_loop, @function
.size builder_lock_upsert_loop, .-builder_lock_upsert_loop
/* end function builder_lock_upsert_loop */

.text
.balign 16
.globl builder_lock_write
builder_lock_write:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x0
	mov	x0, x1
	bl	builder_lock_format_lock
	mov	x1, x0
	mov	x0, x19
	bl	donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_write, @function
.size builder_lock_write, .-builder_lock_write
/* end function builder_lock_write */

.text
.balign 16
builder_lock_format_lock:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x1, str165
	add	x1, x1, #:lo12:str165
	bl	builder_lock_format_deps
	mov	x1, x0
	adrp	x0, str164
	add	x0, x0, #:lo12:str164
	bl	__rt_str_concat
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_format_lock, @function
.size builder_lock_format_lock, .-builder_lock_format_lock
/* end function builder_lock_format_lock */

.text
.balign 16
builder_lock_format_deps:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	str	x22, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L54
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x19, [x1]
	mov	x21, x0
	bl	builder_lock_locked_name
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, str178
	add	x0, x0, #:lo12:str178
	bl	__rt_str_concat
	adrp	x1, str181
	add	x1, x1, #:lo12:str181
	bl	__rt_str_concat
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x22, x0
	bl	builder_lock_locked_git
	mov	x1, x0
	mov	x0, x22
	mov	x22, x0
	adrp	x0, str183
	add	x0, x0, #:lo12:str183
	bl	__rt_str_concat
	adrp	x1, str186
	add	x1, x1, #:lo12:str186
	bl	__rt_str_concat
	mov	x17, x0
	mov	x0, x22
	mov	x22, x17
	bl	builder_lock_locked_rev
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, str188
	add	x0, x0, #:lo12:str188
	bl	__rt_str_concat
	mov	x1, x22
	mov	x22, x1
	adrp	x1, str191
	add	x1, x1, #:lo12:str191
	bl	__rt_str_concat
	mov	x1, x22
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	bl	__rt_str_concat
	mov	x1, x21
	bl	__rt_str_concat
	mov	x1, x0
	mov	x0, x20
	bl	__rt_str_concat
	mov	x1, x0
	mov	x0, x19
	bl	builder_lock_format_deps
	b	.L55
.L54:
	mov	x0, x20
.L55:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldr	x22, [x29, 16]
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_format_deps, @function
.size builder_lock_format_deps, .-builder_lock_format_deps
/* end function builder_lock_format_deps */

.text
.balign 16
.globl builder_lock_write_cached_rev
builder_lock_write_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x1
	adrp	x1, str198
	add	x1, x1, #:lo12:str198
	bl	donna_files_join
	mov	x1, x19
	bl	donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_write_cached_rev, @function
.size builder_lock_write_cached_rev, .-builder_lock_write_cached_rev
/* end function builder_lock_write_cached_rev */

.text
.balign 16
.globl builder_lock_read_cached_rev
builder_lock_read_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	adrp	x1, str201
	add	x1, x1, #:lo12:str201
	bl	donna_files_join
	mov	x19, x0
	bl	donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	.L60
	bl	donna_files_read
	bl	donna_string_trim
	b	.L61
.L60:
	adrp	x0, str209
	add	x0, x0, #:lo12:str209
.L61:
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_read_cached_rev, @function
.size builder_lock_read_cached_rev, .-builder_lock_read_cached_rev
/* end function builder_lock_read_cached_rev */

.text
.balign 16
builder_lock_opt_str:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	bl	parsetoml_parsetoml_get_string
	ldr	x1, [x0]
	cmp	x1, #1
	beq	.L64
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	b	.L65
.L64:
	adrp	x0, str222
	add	x0, x0, #:lo12:str222
.L65:
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_opt_str, @function
.size builder_lock_opt_str, .-builder_lock_opt_str
/* end function builder_lock_opt_str */

.text
.balign 16
__rt_str_concat:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x20, x1
	mov	x21, x0
	mov	x0, x21
	bl	strlen
	mov	x19, x0
	mov	x0, x20
	bl	strlen
	mov	x1, x21
	add	x0, x19, x0
	mov	x19, x1
	mov	x1, #1
	add	x0, x0, x1
	bl	malloc
	mov	x1, x19
	mov	x19, x0
	bl	strcpy
	mov	x1, x20
	mov	x0, x19
	mov	x19, x0
	bl	strcat
	mov	x0, x19
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
.type __rt_str_concat, @function
.size __rt_str_concat, .-__rt_str_concat
/* end function __rt_str_concat */

.section .note.GNU-stack,"",@progbits
