.data
.balign 8
donna_nil:
	.quad 0
/* end data */

.data
.balign 8
str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
str115:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str193:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str194:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str207:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
str210:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str212:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str215:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str217:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str220:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str227:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str230:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str238:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str251:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 16
.globl builder_lock_LockedDep
builder_lock_LockedDep:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x2
	mov	x20, x1
	mov	x19, x0
	mov	x0, #32
	bl	malloc
	mov	x2, x21
	mov	x1, x20
	mov	x3, #0
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x19, [x3]
	mov	x3, #16
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #24
	add	x1, x0, x1
	str	x2, [x1]
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_LockedDep, @function
.size builder_lock_LockedDep, .-builder_lock_LockedDep
/* end function builder_lock_LockedDep */

.text
.balign 16
.globl builder_lock_locked_name
builder_lock_locked_name:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_name, @function
.size builder_lock_locked_name, .-builder_lock_locked_name
/* end function builder_lock_locked_name */

.text
.balign 16
.globl builder_lock_locked_git
builder_lock_locked_git:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #16
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_git, @function
.size builder_lock_locked_git, .-builder_lock_locked_git
/* end function builder_lock_locked_git */

.text
.balign 16
.globl builder_lock_locked_rev
builder_lock_locked_rev:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #24
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_locked_rev, @function
.size builder_lock_locked_rev, .-builder_lock_locked_rev
/* end function builder_lock_locked_rev */

.text
.balign 16
.globl builder_lock_read
builder_lock_read:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x19, x0
	bl	donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	.L21
	bl	donna_files_read
	bl	parsetoml_parsetoml_parse
	mov	x19, x0
	bl	parsetoml_parsetoml_is_err
	mov	x1, x0
	mov	x0, x19
	mov	x2, #16
	sub	sp, sp, x2
	mov	x19, sp
	cmp	x1, #1
	beq	.L19
	bl	parsetoml_parsetoml_unwrap_table
	adrp	x1, str46
	add	x1, x1, #:lo12:str46
	bl	parsetoml_parsetoml_get_table
	mov	x1, #16
	sub	sp, sp, x1
	mov	x20, sp
	ldr	x1, [x0]
	cmp	x1, #1
	beq	.L16
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	mov	x1, #16
	sub	sp, sp, x1
	mov	x21, sp
	ldr	x1, [x0]
	cmp	x1, #4
	beq	.L14
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x21]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	b	.L15
.L14:
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, donna_nil
	add	x1, x1, #:lo12:donna_nil
	bl	builder_lock_collect_locked
	str	x0, [x21]
.L15:
	str	x0, [x20]
	b	.L18
.L16:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x20]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
.L18:
	str	x0, [x19]
	b	.L22
.L19:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	str	x0, [x19]
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
	b	.L22
.L21:
	adrp	x0, donna_nil
	add	x0, x0, #:lo12:donna_nil
.L22:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_read, @function
.size builder_lock_read, .-builder_lock_read
/* end function builder_lock_read */

.text
.balign 16
builder_lock_collect_locked:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	str	x24, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L27
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x19, [x1]
	ldr	x24, [x0]
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, str86
	add	x1, x1, #:lo12:str86
	mov	x21, x0
	bl	builder_lock_opt_str
	mov	x23, x0
	mov	x0, x21
	adrp	x1, str88
	add	x1, x1, #:lo12:str88
	bl	builder_lock_opt_str
	mov	x22, x0
	mov	x0, x19
	mov	x19, x0
	mov	x0, x23
	bl	donna_string_is_empty
	mov	x17, x0
	mov	x0, x19
	mov	x19, x17
	mov	x21, x0
	mov	x0, x22
	bl	donna_string_is_empty
	mov	x1, x0
	mov	x0, x21
	orr	x1, x19, x1
	mov	x2, #16
	sub	sp, sp, x2
	mov	x19, sp
	cmp	x1, #1
	beq	.L26
	mov	x21, x0
	mov	x0, #32
	bl	malloc
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x1, #0
	str	x1, [x21]
	mov	x1, #8
	add	x1, x21, x1
	str	x24, [x1]
	mov	x1, #16
	add	x1, x21, x1
	str	x23, [x1]
	mov	x1, #24
	add	x1, x21, x1
	str	x22, [x1]
	mov	x22, x0
	mov	x0, #24
	bl	malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	builder_lock_collect_locked
	str	x0, [x19]
	b	.L29
.L26:
	mov	x1, x20
	bl	builder_lock_collect_locked
	str	x0, [x19]
	b	.L29
.L27:
	mov	x0, x20
	bl	donna_list_reverse
.L29:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	ldr	x24, [x29, 16]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
.type builder_lock_collect_locked, @function
.size builder_lock_collect_locked, .-builder_lock_collect_locked
/* end function builder_lock_collect_locked */

.text
.balign 16
.globl builder_lock_find_rev
builder_lock_find_rev:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x1
	mov	x1, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L35
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x20, [x1]
	mov	x19, x0
	bl	builder_lock_locked_name
	mov	x1, x21
	mov	x21, x1
	bl	donna_string_equal
	mov	x1, x21
	mov	x2, x0
	mov	x0, x19
	mov	x3, #16
	sub	sp, sp, x3
	mov	x19, sp
	cmp	x2, #1
	beq	.L34
	mov	x0, x20
	bl	builder_lock_find_rev
	str	x0, [x19]
	b	.L36
.L34:
	bl	builder_lock_locked_rev
	str	x0, [x19]
	b	.L36
.L35:
	adrp	x0, str115
	add	x0, x0, #:lo12:str115
.L36:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_find_rev, @function
.size builder_lock_find_rev, .-builder_lock_find_rev
/* end function builder_lock_find_rev */

.text
.balign 16
.globl builder_lock_upsert
builder_lock_upsert:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x2, donna_nil
	add	x2, x2, #:lo12:donna_nil
	bl	builder_lock_upsert_loop
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_upsert, @function
.size builder_lock_upsert, .-builder_lock_upsert
/* end function builder_lock_upsert */

.text
.balign 16
builder_lock_upsert_loop:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	ldr	x3, [x0]
	cmp	x3, #0
	beq	.L44
	mov	x21, x2
	mov	x2, #8
	add	x2, x0, x2
	ldr	x22, [x2]
	mov	x19, x1
	mov	x1, #16
	add	x0, x0, x1
	ldr	x20, [x0]
	mov	x0, x22
	bl	builder_lock_locked_name
	mov	x23, x0
	mov	x0, x19
	bl	builder_lock_locked_name
	mov	x1, x0
	mov	x0, x23
	bl	donna_string_equal
	mov	x1, x19
	mov	x23, x1
	mov	x1, #16
	sub	sp, sp, x1
	mov	x19, sp
	cmp	x0, #1
	beq	.L42
	mov	x0, #24
	bl	malloc
	mov	x1, x23
	mov	x2, x0
	mov	x0, #1
	str	x0, [x2]
	mov	x0, #8
	add	x0, x2, x0
	str	x22, [x0]
	mov	x0, #16
	add	x0, x2, x0
	str	x21, [x0]
	mov	x21, x1
	mov	x0, x20
	bl	builder_lock_upsert_loop
	str	x0, [x19]
	b	.L46
.L42:
	mov	x2, x21
	mov	x21, x23
	mov	x0, x2
	bl	donna_list_reverse
	mov	x22, x0
	mov	x0, #24
	bl	malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	donna_list_append
	str	x0, [x19]
	b	.L46
.L44:
	mov	x20, x2
	mov	x19, x1
	mov	x0, #24
	bl	malloc
	mov	x2, x20
	mov	x1, x19
	mov	x3, #1
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #16
	add	x1, x0, x1
	str	x2, [x1]
	bl	donna_list_reverse
.L46:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
.type builder_lock_upsert_loop, @function
.size builder_lock_upsert_loop, .-builder_lock_upsert_loop
/* end function builder_lock_upsert_loop */

.text
.balign 16
.globl builder_lock_remove
builder_lock_remove:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x2, donna_nil
	add	x2, x2, #:lo12:donna_nil
	bl	builder_lock_remove_loop
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_remove, @function
.size builder_lock_remove, .-builder_lock_remove
/* end function builder_lock_remove */

.text
.balign 16
builder_lock_remove_loop:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	mov	x20, x2
	ldr	x2, [x0]
	cmp	x2, #0
	beq	.L54
	mov	x2, #8
	add	x2, x0, x2
	ldr	x21, [x2]
	mov	x22, x1
	mov	x1, #16
	add	x0, x0, x1
	ldr	x0, [x0]
	mov	x19, x0
	mov	x0, x21
	bl	builder_lock_locked_name
	mov	x1, x22
	mov	x23, x1
	bl	donna_string_equal
	mov	x1, x0
	mov	x0, x19
	mov	x2, #16
	sub	sp, sp, x2
	mov	x19, sp
	cmp	x1, #1
	beq	.L52
	mov	x22, x0
	mov	x0, #24
	bl	malloc
	mov	x1, x23
	mov	x2, x0
	mov	x0, x22
	mov	x3, #1
	str	x3, [x2]
	mov	x3, #8
	add	x3, x2, x3
	str	x21, [x3]
	mov	x3, #16
	add	x3, x2, x3
	str	x20, [x3]
	bl	builder_lock_remove_loop
	str	x0, [x19]
	b	.L56
.L52:
	mov	x1, x23
	mov	x2, x20
	bl	builder_lock_remove_loop
	str	x0, [x19]
	b	.L56
.L54:
	mov	x0, x20
	bl	donna_list_reverse
.L56:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
.type builder_lock_remove_loop, @function
.size builder_lock_remove_loop, .-builder_lock_remove_loop
/* end function builder_lock_remove_loop */

.text
.balign 16
.globl builder_lock_write
builder_lock_write:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x0
	mov	x0, x1
	bl	builder_lock_format_lock
	mov	x1, x0
	mov	x0, x19
	bl	donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_write, @function
.size builder_lock_write, .-builder_lock_write
/* end function builder_lock_write */

.text
.balign 16
builder_lock_format_lock:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x1, str194
	add	x1, x1, #:lo12:str194
	bl	builder_lock_format_deps
	mov	x1, x0
	adrp	x0, str193
	add	x0, x0, #:lo12:str193
	bl	__rt_str_concat
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_format_lock, @function
.size builder_lock_format_lock, .-builder_lock_format_lock
/* end function builder_lock_format_lock */

.text
.balign 16
builder_lock_format_deps:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	str	x22, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	.L63
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x19, [x1]
	mov	x21, x0
	bl	builder_lock_locked_name
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, str207
	add	x0, x0, #:lo12:str207
	bl	__rt_str_concat
	adrp	x1, str210
	add	x1, x1, #:lo12:str210
	bl	__rt_str_concat
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x22, x0
	bl	builder_lock_locked_git
	mov	x1, x0
	mov	x0, x22
	mov	x22, x0
	adrp	x0, str212
	add	x0, x0, #:lo12:str212
	bl	__rt_str_concat
	adrp	x1, str215
	add	x1, x1, #:lo12:str215
	bl	__rt_str_concat
	mov	x17, x0
	mov	x0, x22
	mov	x22, x17
	bl	builder_lock_locked_rev
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, str217
	add	x0, x0, #:lo12:str217
	bl	__rt_str_concat
	mov	x1, x22
	mov	x22, x1
	adrp	x1, str220
	add	x1, x1, #:lo12:str220
	bl	__rt_str_concat
	mov	x1, x22
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	bl	__rt_str_concat
	mov	x1, x21
	bl	__rt_str_concat
	mov	x1, x0
	mov	x0, x20
	bl	__rt_str_concat
	mov	x1, x0
	mov	x0, x19
	bl	builder_lock_format_deps
	b	.L64
.L63:
	mov	x0, x20
.L64:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldr	x22, [x29, 16]
	ldp	x29, x30, [sp], 48
	ret
.type builder_lock_format_deps, @function
.size builder_lock_format_deps, .-builder_lock_format_deps
/* end function builder_lock_format_deps */

.text
.balign 16
.globl builder_lock_write_cached_rev
builder_lock_write_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x1
	adrp	x1, str227
	add	x1, x1, #:lo12:str227
	bl	donna_files_join
	mov	x1, x19
	bl	donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_write_cached_rev, @function
.size builder_lock_write_cached_rev, .-builder_lock_write_cached_rev
/* end function builder_lock_write_cached_rev */

.text
.balign 16
.globl builder_lock_read_cached_rev
builder_lock_read_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	adrp	x1, str230
	add	x1, x1, #:lo12:str230
	bl	donna_files_join
	mov	x19, x0
	bl	donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	.L69
	bl	donna_files_read
	bl	donna_string_trim
	b	.L70
.L69:
	adrp	x0, str238
	add	x0, x0, #:lo12:str238
.L70:
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
.type builder_lock_read_cached_rev, @function
.size builder_lock_read_cached_rev, .-builder_lock_read_cached_rev
/* end function builder_lock_read_cached_rev */

.text
.balign 16
builder_lock_opt_str:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	bl	parsetoml_parsetoml_get_string
	ldr	x1, [x0]
	cmp	x1, #1
	beq	.L73
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	b	.L74
.L73:
	adrp	x0, str251
	add	x0, x0, #:lo12:str251
.L74:
	ldp	x29, x30, [sp], 16
	ret
.type builder_lock_opt_str, @function
.size builder_lock_opt_str, .-builder_lock_opt_str
/* end function builder_lock_opt_str */

.text
.balign 16
__rt_str_concat:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x20, x1
	mov	x21, x0
	mov	x0, x21
	bl	strlen
	mov	x19, x0
	mov	x0, x20
	bl	strlen
	mov	x1, x21
	add	x0, x19, x0
	mov	x19, x1
	mov	x1, #1
	add	x0, x0, x1
	bl	malloc
	mov	x1, x19
	mov	x19, x0
	bl	strcpy
	mov	x1, x20
	mov	x0, x19
	mov	x19, x0
	bl	strcat
	mov	x0, x19
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
.type __rt_str_concat, @function
.size __rt_str_concat, .-__rt_str_concat
/* end function __rt_str_concat */

.section .note.GNU-stack,"",@progbits
