.data
.balign 8
_donna_nil:
	.quad 0
/* end data */

.data
.balign 8
_str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
_str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
_str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
_str115:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str167:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str168:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str181:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
_str184:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str186:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
_str189:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str191:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
_str194:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str201:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
_str204:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
_str212:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str225:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 16
.globl _builder_lock_LockedDep
_builder_lock_LockedDep:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rdx, %r13
	movq %rsi, %r12
	movq %rdi, %rbx
	movl $32, %edi
	callq _malloc
	movq %r13, %rdx
	movq %r12, %rsi
	movq %rbx, %rdi
	movq $0, (%rax)
	movq %rdi, 8(%rax)
	movq %rsi, 16(%rax)
	movq %rdx, 24(%rax)
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_LockedDep */

.text
.balign 16
.globl _builder_lock_locked_name
_builder_lock_locked_name:
	endbr64
	movq 8(%rdi), %rax
	ret
/* end function builder_lock_locked_name */

.text
.balign 16
.globl _builder_lock_locked_git
_builder_lock_locked_git:
	endbr64
	movq 16(%rdi), %rax
	ret
/* end function builder_lock_locked_git */

.text
.balign 16
.globl _builder_lock_locked_rev
_builder_lock_locked_rev:
	endbr64
	movq 24(%rdi), %rax
	ret
/* end function builder_lock_locked_rev */

.text
.balign 16
.globl _builder_lock_read
_builder_lock_read:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rdi, %rbx
	callq _donna_files_exists
	movq %rbx, %rdi
	cmpq $0, %rax
	jz Lbb18
	callq _donna_files_read
	movq %rax, %rdi
	callq _parsetoml_parsetoml_parse
	movq %rax, %rdi
	movq %rdi, %rbx
	callq _parsetoml_parsetoml_is_err
	movq %rbx, %rdi
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz Lbb17
	callq _parsetoml_parsetoml_unwrap_table
	movq %rax, %rdi
	leaq _str46(%rip), %rsi
	callq _parsetoml_parsetoml_get_table
	subq $16, %rsp
	movq %rsp, %r12
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz Lbb15
	movq 8(%rax), %rax
	subq $16, %rsp
	movq %rsp, %r13
	movq (%rax), %rcx
	cmpq $4, %rcx
	jz Lbb13
	leaq _donna_nil(%rip), %rax
	movq %rax, (%r13)
	leaq _donna_nil(%rip), %rax
	jmp Lbb14
Lbb13:
	movq 8(%rax), %rdi
	leaq _donna_nil(%rip), %rsi
	callq _builder_lock_collect_locked
	movq %rax, (%r13)
Lbb14:
	movq %rax, (%r12)
	jmp Lbb16
Lbb15:
	leaq _donna_nil(%rip), %rax
	movq %rax, (%r12)
	leaq _donna_nil(%rip), %rax
Lbb16:
	movq %rax, (%rbx)
	jmp Lbb19
Lbb17:
	leaq _donna_nil(%rip), %rax
	movq %rax, (%rbx)
	leaq _donna_nil(%rip), %rax
	jmp Lbb19
Lbb18:
	leaq _donna_nil(%rip), %rax
Lbb19:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_read */

.text
.balign 16
_builder_lock_collect_locked:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $24, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rsi, %r12
	movq (%rdi), %rax
	cmpq $0, %rax
	jz Lbb24
	movq 8(%rdi), %rax
	movq 16(%rdi), %rbx
	movq (%rax), %rcx
	movq %rcx, -16(%rbp)
	movq 8(%rax), %rdi
	leaq _str86(%rip), %rsi
	movq %rdi, %r13
	callq _builder_lock_opt_str
	movq %r13, %rdi
	movq %rax, %r15
	leaq _str88(%rip), %rsi
	callq _builder_lock_opt_str
	movq %rbx, %rdi
	movq %rax, %r14
	movq %rdi, %rbx
	movq %r15, %rdi
	callq _donna_string_is_empty
	movq %rbx, %rdi
	movq %rax, %rbx
	movq %rdi, %r13
	movq %r14, %rdi
	callq _donna_string_is_empty
	movq %r13, %rdi
	orq %rbx, %rax
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz Lbb23
	movq %rdi, %r13
	movl $32, %edi
	callq _malloc
	movq %r13, %rdi
	movq %rax, %r13
	movq -16(%rbp), %rax
	movq $0, (%r13)
	movq %rax, 8(%r13)
	movq %r15, 16(%r13)
	movq %r14, 24(%r13)
	movq %rdi, %r14
	movl $24, %edi
	callq _malloc
	movq %r14, %rdi
	movq %rax, %rsi
	movq $1, (%rsi)
	movq %r13, 8(%rsi)
	movq %r12, 16(%rsi)
	callq _builder_lock_collect_locked
	movq %rax, (%rbx)
	jmp Lbb26
Lbb23:
	movq %r12, %rsi
	callq _builder_lock_collect_locked
	movq %rax, (%rbx)
	jmp Lbb26
Lbb24:
	movq %r12, %rdi
	callq _donna_list_reverse
Lbb26:
	movq %rbp, %rsp
	subq $64, %rsp
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_collect_locked */

.text
.balign 16
.globl _builder_lock_find_rev
_builder_lock_find_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rsi, %r13
	movq %rdi, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz Lbb32
	movq 8(%rax), %rdi
	movq 16(%rax), %r12
	movq %rdi, %rbx
	callq _builder_lock_locked_name
	movq %r13, %rsi
	movq %rax, %rdi
	movq %rsi, %r13
	callq _donna_string_equal
	movq %r13, %rsi
	movq %rbx, %rdi
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz Lbb31
	movq %r12, %rdi
	callq _builder_lock_find_rev
	movq %rax, (%rbx)
	jmp Lbb33
Lbb31:
	callq _builder_lock_locked_rev
	movq %rax, (%rbx)
	jmp Lbb33
Lbb32:
	leaq _str115(%rip), %rax
Lbb33:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_find_rev */

.text
.balign 16
.globl _builder_lock_upsert
_builder_lock_upsert:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	leaq _donna_nil(%rip), %rdx
	callq _builder_lock_upsert_loop
	leave
	ret
/* end function builder_lock_upsert */

.text
.balign 16
_builder_lock_upsert_loop:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rdx, %r13
	movq %rsi, %r15
	movq (%rdi), %rax
	cmpq $0, %rax
	jz Lbb41
	movq 8(%rdi), %r14
	movq 16(%rdi), %r12
	movq %r14, %rdi
	callq _builder_lock_locked_name
	movq %rax, %rdi
	movq %rdi, %rbx
	movq %r15, %rdi
	callq _builder_lock_locked_name
	movq %rbx, %rdi
	movq %rax, %rsi
	callq _donna_string_equal
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz Lbb39
	movl $24, %edi
	callq _malloc
	movq %r15, %rsi
	movq %rax, %rdx
	movq $1, (%rdx)
	movq %r14, 8(%rdx)
	movq %r13, 16(%rdx)
	movq %rsi, %r13
	movq %r12, %rdi
	callq _builder_lock_upsert_loop
	movq %rax, (%rbx)
	jmp Lbb43
Lbb39:
	movq %r13, %rdx
	movq %r15, %r13
	movq %rdx, %rdi
	callq _donna_list_reverse
	movq %rax, %rdi
	movq %rdi, %r14
	movl $24, %edi
	callq _malloc
	movq %r14, %rdi
	movq %rax, %rsi
	movq $1, (%rsi)
	movq %r13, 8(%rsi)
	movq %r12, 16(%rsi)
	callq _donna_list_append
	movq %rax, (%rbx)
	jmp Lbb43
Lbb41:
	movq %r13, %r12
	movq %r15, %rbx
	movl $24, %edi
	callq _malloc
	movq %r12, %rdx
	movq %rbx, %rsi
	movq %rax, %rdi
	movq $1, (%rdi)
	movq %rsi, 8(%rdi)
	movq %rdx, 16(%rdi)
	callq _donna_list_reverse
Lbb43:
	movq %rbp, %rsp
	subq $48, %rsp
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_upsert_loop */

.text
.balign 16
.globl _builder_lock_write
_builder_lock_write:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	movq %rdi, %rbx
	movq %rsi, %rdi
	callq _builder_lock_format_lock
	movq %rbx, %rdi
	movq %rax, %rsi
	callq _donna_files_write
	popq %rbx
	leave
	ret
/* end function builder_lock_write */

.text
.balign 16
_builder_lock_format_lock:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	leaq _str168(%rip), %rsi
	callq _builder_lock_format_deps
	movq %rax, %rsi
	leaq _str167(%rip), %rdi
	callq ___rt_str_concat
	leave
	ret
/* end function builder_lock_format_lock */

.text
.balign 16
_builder_lock_format_deps:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	movq %rsi, %rbx
	movq %rdi, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz Lbb50
	movq 8(%rax), %rdi
	movq 16(%rax), %r12
	movq %rdi, %r13
	callq _builder_lock_locked_name
	movq %r13, %rdi
	movq %rax, %rsi
	movq %rdi, %r13
	leaq _str181(%rip), %rdi
	callq ___rt_str_concat
	movq %rax, %rdi
	leaq _str184(%rip), %rsi
	callq ___rt_str_concat
	movq %r13, %rdi
	movq %rax, %r13
	movq %rdi, %r14
	callq _builder_lock_locked_git
	movq %r14, %rdi
	movq %rax, %rsi
	movq %rdi, %r14
	leaq _str186(%rip), %rdi
	callq ___rt_str_concat
	movq %rax, %rdi
	leaq _str189(%rip), %rsi
	callq ___rt_str_concat
	movq %r14, %rdi
	movq %rax, %r14
	callq _builder_lock_locked_rev
	movq %r13, %rdi
	movq %rax, %rsi
	movq %rdi, %r13
	leaq _str191(%rip), %rdi
	callq ___rt_str_concat
	movq %r14, %rsi
	movq %rax, %rdi
	movq %rsi, %r14
	leaq _str194(%rip), %rsi
	callq ___rt_str_concat
	movq %r14, %rsi
	movq %r13, %rdi
	movq %rax, %r13
	callq ___rt_str_concat
	movq %r13, %rsi
	movq %rax, %rdi
	callq ___rt_str_concat
	movq %r12, %rdi
	movq %rax, %rsi
	movq %rbx, %rax
	movq %rdi, %rbx
	movq %rax, %rdi
	callq ___rt_str_concat
	movq %rbx, %rdi
	movq %rax, %rsi
	callq _builder_lock_format_deps
	jmp Lbb51
Lbb50:
	movq %rbx, %rax
Lbb51:
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_format_deps */

.text
.balign 16
.globl _builder_lock_write_cached_rev
_builder_lock_write_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	movq %rsi, %rbx
	leaq _str201(%rip), %rsi
	callq _donna_files_join
	movq %rbx, %rsi
	movq %rax, %rdi
	callq _donna_files_write
	popq %rbx
	leave
	ret
/* end function builder_lock_write_cached_rev */

.text
.balign 16
.globl _builder_lock_read_cached_rev
_builder_lock_read_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	leaq _str204(%rip), %rsi
	callq _donna_files_join
	movq %rax, %rdi
	movq %rdi, %rbx
	callq _donna_files_exists
	movq %rbx, %rdi
	cmpq $0, %rax
	jz Lbb56
	callq _donna_files_read
	movq %rax, %rdi
	callq _donna_string_trim
	jmp Lbb57
Lbb56:
	leaq _str212(%rip), %rax
Lbb57:
	popq %rbx
	leave
	ret
/* end function builder_lock_read_cached_rev */

.text
.balign 16
_builder_lock_opt_str:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	callq _parsetoml_parsetoml_get_string
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz Lbb60
	movq 8(%rax), %rax
	jmp Lbb61
Lbb60:
	leaq _str225(%rip), %rax
Lbb61:
	leave
	ret
/* end function builder_lock_opt_str */

.text
.balign 16
___rt_str_concat:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rsi, %r12
	movq %rdi, %rbx
	movq %rbx, %rdi
	callq _strlen
	movq %rax, %r13
	movq %r12, %rdi
	callq _strlen
	addq %r13, %rax
	movq %rax, %rdi
	addq $1, %rdi
	callq _malloc
	movq %rbx, %rsi
	movq %rax, %rbx
	movq %rbx, %rdi
	callq _strcpy
	movq %r12, %rsi
	movq %rbx, %rdi
	callq _strcat
	movq %rbx, %rax
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function __rt_str_concat */

