.data
.balign 8
donna_nil:
	.quad 0
/* end data */

.data
.balign 8
str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
str115:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str167:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str168:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str181:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
str184:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str186:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str189:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str191:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str194:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str201:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str204:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str212:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str225:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 16
.globl builder_lock_LockedDep
builder_lock_LockedDep:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %rsi
	pushq %rdi
	movq %r8, %rbx
	movq %rdx, %rdi
	subq $32, %rsp
	movq %rcx, %rsi
	movl $32, %ecx
	callq malloc
	movq %rbx, %r8
	movq %rdi, %rdx
	movq %rsi, %rcx
	subq $-32, %rsp
	movq $0, (%rax)
	movq %rcx, 8(%rax)
	movq %rdx, 16(%rax)
	movq %r8, 24(%rax)
	popq %rdi
	popq %rsi
	popq %rbx
	leave
	ret
/* end function builder_lock_LockedDep */

.text
.balign 16
.globl builder_lock_locked_name
builder_lock_locked_name:
	endbr64
	movq 8(%rcx), %rax
	ret
/* end function builder_lock_locked_name */

.text
.balign 16
.globl builder_lock_locked_git
builder_lock_locked_git:
	endbr64
	movq 16(%rcx), %rax
	ret
/* end function builder_lock_locked_git */

.text
.balign 16
.globl builder_lock_locked_rev
builder_lock_locked_rev:
	endbr64
	movq 24(%rcx), %rax
	ret
/* end function builder_lock_locked_rev */

.text
.balign 16
.globl builder_lock_read
builder_lock_read:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %rsi
	pushq %rdi
	subq $32, %rsp
	movq %rcx, %rsi
	callq donna_files_exists
	movq %rsi, %rcx
	subq $-32, %rsp
	cmpq $0, %rax
	jz Lbb18
	subq $32, %rsp
	callq donna_files_read
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	callq parsetoml_parsetoml_parse
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rsi
	callq parsetoml_parsetoml_is_err
	movq %rsi, %rcx
	subq $-32, %rsp
	subq $16, %rsp
	movq %rsp, %rsi
	cmpq $1, %rax
	jz Lbb17
	subq $32, %rsp
	callq parsetoml_parsetoml_unwrap_table
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	leaq str46(%rip), %rdx
	callq parsetoml_parsetoml_get_table
	subq $-32, %rsp
	subq $16, %rsp
	movq %rsp, %rdi
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz Lbb15
	movq 8(%rax), %rax
	subq $16, %rsp
	movq %rsp, %rbx
	movq (%rax), %rcx
	cmpq $4, %rcx
	jz Lbb13
	leaq donna_nil(%rip), %rax
	movq %rax, (%rbx)
	leaq donna_nil(%rip), %rax
	jmp Lbb14
Lbb13:
	movq 8(%rax), %rcx
	subq $32, %rsp
	leaq donna_nil(%rip), %rdx
	callq builder_lock_collect_locked
	subq $-32, %rsp
	movq %rax, (%rbx)
Lbb14:
	movq %rax, (%rdi)
	jmp Lbb16
Lbb15:
	leaq donna_nil(%rip), %rax
	movq %rax, (%rdi)
	leaq donna_nil(%rip), %rax
Lbb16:
	movq %rax, (%rsi)
	jmp Lbb19
Lbb17:
	leaq donna_nil(%rip), %rax
	movq %rax, (%rsi)
	leaq donna_nil(%rip), %rax
	jmp Lbb19
Lbb18:
	leaq donna_nil(%rip), %rax
Lbb19:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %rdi
	popq %rsi
	popq %rbx
	leave
	ret
/* end function builder_lock_read */

.text
.balign 16
builder_lock_collect_locked:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %rsi
	pushq %rdi
	movq %rdx, %rdi
	movq (%rcx), %rax
	cmpq $0, %rax
	jz Lbb24
	movq 8(%rcx), %rax
	movq 16(%rcx), %rsi
	movq (%rax), %r14
	movq 8(%rax), %rcx
	subq $32, %rsp
	leaq str86(%rip), %rdx
	movq %rcx, %rbx
	callq builder_lock_opt_str
	movq %rbx, %rcx
	movq %rax, %r13
	subq $-32, %rsp
	subq $32, %rsp
	leaq str88(%rip), %rdx
	callq builder_lock_opt_str
	movq %rsi, %rcx
	movq %rax, %r12
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rsi
	movq %r13, %rcx
	callq donna_string_is_empty
	movq %rsi, %rcx
	movq %rax, %rsi
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rbx
	movq %r12, %rcx
	callq donna_string_is_empty
	movq %rbx, %rcx
	subq $-32, %rsp
	orq %rsi, %rax
	subq $16, %rsp
	movq %rsp, %rsi
	cmpq $1, %rax
	jz Lbb23
	subq $32, %rsp
	movq %rcx, %rbx
	movl $32, %ecx
	callq malloc
	movq %rbx, %rcx
	movq %rax, %rbx
	subq $-32, %rsp
	movq $0, (%rbx)
	movq %r14, 8(%rbx)
	movq %r13, 16(%rbx)
	movq %r12, 24(%rbx)
	subq $32, %rsp
	movq %rcx, %r12
	movl $24, %ecx
	callq malloc
	movq %r12, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	movq $1, (%rdx)
	movq %rbx, 8(%rdx)
	movq %rdi, 16(%rdx)
	subq $32, %rsp
	callq builder_lock_collect_locked
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb26
Lbb23:
	subq $32, %rsp
	movq %rdi, %rdx
	callq builder_lock_collect_locked
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb26
Lbb24:
	movq %rdi, %rcx
	subq $32, %rsp
	callq donna_list_reverse
	subq $-32, %rsp
Lbb26:
	movq %rbp, %rsp
	subq $48, %rsp
	popq %rdi
	popq %rsi
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_collect_locked */

.text
.balign 16
.globl builder_lock_find_rev
builder_lock_find_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %rsi
	pushq %rdi
	movq %rdx, %rbx
	movq %rcx, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz Lbb32
	movq 8(%rax), %rcx
	movq 16(%rax), %rdi
	subq $32, %rsp
	movq %rcx, %rsi
	callq builder_lock_locked_name
	movq %rbx, %rdx
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rdx, %rbx
	callq donna_string_equal
	movq %rbx, %rdx
	movq %rsi, %rcx
	subq $-32, %rsp
	subq $16, %rsp
	movq %rsp, %rsi
	cmpq $1, %rax
	jz Lbb31
	movq %rdi, %rcx
	subq $32, %rsp
	callq builder_lock_find_rev
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb33
Lbb31:
	subq $32, %rsp
	callq builder_lock_locked_rev
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb33
Lbb32:
	leaq str115(%rip), %rax
Lbb33:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %rdi
	popq %rsi
	popq %rbx
	leave
	ret
/* end function builder_lock_find_rev */

.text
.balign 16
.globl builder_lock_upsert
builder_lock_upsert:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $32, %rsp
	leaq donna_nil(%rip), %r8
	callq builder_lock_upsert_loop
	subq $-32, %rsp
	leave
	ret
/* end function builder_lock_upsert */

.text
.balign 16
builder_lock_upsert_loop:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %rsi
	pushq %rdi
	movq %r8, %rbx
	movq %rdx, %r13
	movq (%rcx), %rax
	cmpq $0, %rax
	jz Lbb41
	movq 8(%rcx), %r12
	movq 16(%rcx), %rdi
	subq $32, %rsp
	movq %r12, %rcx
	callq builder_lock_locked_name
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rsi
	movq %r13, %rcx
	callq builder_lock_locked_name
	movq %rsi, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	callq donna_string_equal
	subq $-32, %rsp
	subq $16, %rsp
	movq %rsp, %rsi
	cmpq $1, %rax
	jz Lbb39
	subq $32, %rsp
	movl $24, %ecx
	callq malloc
	movq %r13, %rdx
	movq %rax, %r8
	subq $-32, %rsp
	movq $1, (%r8)
	movq %r12, 8(%r8)
	movq %rbx, 16(%r8)
	subq $32, %rsp
	movq %rdx, %rbx
	movq %rdi, %rcx
	callq builder_lock_upsert_loop
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb43
Lbb39:
	movq %rbx, %r8
	movq %r13, %rbx
	subq $32, %rsp
	movq %r8, %rcx
	callq donna_list_reverse
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %r12
	movl $24, %ecx
	callq malloc
	movq %r12, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	movq $1, (%rdx)
	movq %rbx, 8(%rdx)
	movq %rdi, 16(%rdx)
	subq $32, %rsp
	callq donna_list_append
	subq $-32, %rsp
	movq %rax, (%rsi)
	jmp Lbb43
Lbb41:
	movq %rbx, %rdi
	movq %r13, %rsi
	subq $32, %rsp
	movl $24, %ecx
	callq malloc
	movq %rdi, %r8
	movq %rsi, %rdx
	movq %rax, %rcx
	subq $-32, %rsp
	movq $1, (%rcx)
	movq %rdx, 8(%rcx)
	movq %r8, 16(%rcx)
	subq $32, %rsp
	callq donna_list_reverse
	subq $-32, %rsp
Lbb43:
	movq %rbp, %rsp
	subq $48, %rsp
	popq %rdi
	popq %rsi
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_upsert_loop */

.text
.balign 16
.globl builder_lock_write
builder_lock_write:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rsi
	movq %rcx, %rsi
	movq %rdx, %rcx
	subq $32, %rsp
	callq builder_lock_format_lock
	movq %rsi, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	callq donna_files_write
	subq $-32, %rsp
	popq %rsi
	leave
	ret
/* end function builder_lock_write */

.text
.balign 16
builder_lock_format_lock:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $32, %rsp
	leaq str168(%rip), %rdx
	callq builder_lock_format_deps
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	leaq str167(%rip), %rcx
	callq __rt_str_concat
	subq $-32, %rsp
	leave
	ret
/* end function builder_lock_format_lock */

.text
.balign 16
builder_lock_format_deps:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	pushq %rbx
	pushq %r12
	pushq %rsi
	pushq %rdi
	movq %rdx, %rsi
	movq %rcx, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz Lbb50
	movq 8(%rax), %rcx
	movq 16(%rax), %rdi
	subq $32, %rsp
	movq %rcx, %rbx
	callq builder_lock_locked_name
	movq %rbx, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rbx
	leaq str181(%rip), %rcx
	callq __rt_str_concat
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	leaq str184(%rip), %rdx
	callq __rt_str_concat
	movq %rbx, %rcx
	movq %rax, %rbx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %r12
	callq builder_lock_locked_git
	movq %r12, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %r12
	leaq str186(%rip), %rcx
	callq __rt_str_concat
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	leaq str189(%rip), %rdx
	callq __rt_str_concat
	movq %r12, %rcx
	movq %rax, %r12
	subq $-32, %rsp
	subq $32, %rsp
	callq builder_lock_locked_rev
	movq %rbx, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rbx
	leaq str191(%rip), %rcx
	callq __rt_str_concat
	movq %r12, %rdx
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rdx, %r12
	leaq str194(%rip), %rdx
	callq __rt_str_concat
	movq %r12, %rdx
	movq %rbx, %rcx
	movq %rax, %rbx
	subq $-32, %rsp
	subq $32, %rsp
	callq __rt_str_concat
	movq %rbx, %rdx
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	callq __rt_str_concat
	movq %rdi, %rcx
	movq %rax, %rdx
	movq %rsi, %rax
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rsi
	movq %rax, %rcx
	callq __rt_str_concat
	movq %rsi, %rcx
	movq %rax, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	callq builder_lock_format_deps
	subq $-32, %rsp
	jmp Lbb51
Lbb50:
	movq %rsi, %rax
Lbb51:
	popq %rdi
	popq %rsi
	popq %r12
	popq %rbx
	leave
	ret
/* end function builder_lock_format_deps */

.text
.balign 16
.globl builder_lock_write_cached_rev
builder_lock_write_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rsi
	subq $32, %rsp
	movq %rdx, %rsi
	leaq str201(%rip), %rdx
	callq donna_files_join
	movq %rsi, %rdx
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	callq donna_files_write
	subq $-32, %rsp
	popq %rsi
	leave
	ret
/* end function builder_lock_write_cached_rev */

.text
.balign 16
.globl builder_lock_read_cached_rev
builder_lock_read_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rsi
	subq $32, %rsp
	leaq str204(%rip), %rdx
	callq donna_files_join
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rcx, %rsi
	callq donna_files_exists
	movq %rsi, %rcx
	subq $-32, %rsp
	cmpq $0, %rax
	jz Lbb56
	subq $32, %rsp
	callq donna_files_read
	movq %rax, %rcx
	subq $-32, %rsp
	subq $32, %rsp
	callq donna_string_trim
	subq $-32, %rsp
	jmp Lbb57
Lbb56:
	leaq str212(%rip), %rax
Lbb57:
	popq %rsi
	leave
	ret
/* end function builder_lock_read_cached_rev */

.text
.balign 16
builder_lock_opt_str:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $32, %rsp
	callq parsetoml_parsetoml_get_string
	subq $-32, %rsp
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz Lbb60
	movq 8(%rax), %rax
	jmp Lbb61
Lbb60:
	leaq str225(%rip), %rax
Lbb61:
	leave
	ret
/* end function builder_lock_opt_str */

.text
.balign 16
__rt_str_concat:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %rsi
	pushq %rdi
	movq %rdx, %rdi
	movq %rcx, %rsi
	subq $32, %rsp
	movq %rsi, %rcx
	callq strlen
	movq %rax, %rbx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rdi, %rcx
	callq strlen
	subq $-32, %rsp
	addq %rbx, %rax
	movq %rax, %rcx
	addq $1, %rcx
	subq $32, %rsp
	callq malloc
	movq %rsi, %rdx
	movq %rax, %rsi
	subq $-32, %rsp
	subq $32, %rsp
	movq %rsi, %rcx
	callq strcpy
	movq %rdi, %rdx
	subq $-32, %rsp
	subq $32, %rsp
	movq %rsi, %rcx
	callq strcat
	movq %rsi, %rax
	subq $-32, %rsp
	popq %rdi
	popq %rsi
	popq %rbx
	leave
	ret
/* end function __rt_str_concat */

