.data
.balign 8
_donna_nil:
	.quad 0
/* end data */

.data
.balign 8
_str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
_str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
_str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
_str112:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str164:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str165:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str178:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
_str181:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str183:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
_str186:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str188:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
_str191:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
_str198:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
_str201:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
_str209:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
_str222:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 4
.globl _builder_lock_LockedDep
_builder_lock_LockedDep:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x2
	mov	x20, x1
	mov	x19, x0
	mov	x0, #32
	bl	_malloc
	mov	x2, x21
	mov	x1, x20
	mov	x3, #0
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x19, [x3]
	mov	x3, #16
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #24
	add	x1, x0, x1
	str	x2, [x1]
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
/* end function builder_lock_LockedDep */

.text
.balign 4
.globl _builder_lock_locked_name
_builder_lock_locked_name:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_locked_name */

.text
.balign 4
.globl _builder_lock_locked_git
_builder_lock_locked_git:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #16
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_locked_git */

.text
.balign 4
.globl _builder_lock_locked_rev
_builder_lock_locked_rev:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	mov	x1, #24
	add	x0, x0, x1
	ldr	x0, [x0]
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_locked_rev */

.text
.balign 4
.globl _builder_lock_read
_builder_lock_read:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x19, x0
	bl	_donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	L21
	bl	_donna_files_read
	bl	_parsetoml_parsetoml_parse
	mov	x19, x0
	bl	_parsetoml_parsetoml_is_err
	mov	x1, x0
	mov	x0, x19
	mov	x2, #16
	sub	sp, sp, x2
	mov	x19, sp
	cmp	x1, #1
	beq	L19
	bl	_parsetoml_parsetoml_unwrap_table
	adrp	x1, _str46@page
	add	x1, x1, _str46@pageoff
	bl	_parsetoml_parsetoml_get_table
	mov	x1, #16
	sub	sp, sp, x1
	mov	x20, sp
	ldr	x1, [x0]
	cmp	x1, #1
	beq	L16
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	mov	x1, #16
	sub	sp, sp, x1
	mov	x21, sp
	ldr	x1, [x0]
	cmp	x1, #4
	beq	L14
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
	str	x0, [x21]
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
	b	L15
L14:
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, _donna_nil@page
	add	x1, x1, _donna_nil@pageoff
	bl	_builder_lock_collect_locked
	str	x0, [x21]
L15:
	str	x0, [x20]
	b	L18
L16:
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
	str	x0, [x20]
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
L18:
	str	x0, [x19]
	b	L22
L19:
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
	str	x0, [x19]
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
	b	L22
L21:
	adrp	x0, _donna_nil@page
	add	x0, x0, _donna_nil@pageoff
L22:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
/* end function builder_lock_read */

.text
.balign 4
_builder_lock_collect_locked:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	str	x24, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	L28
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x21, [x1]
	ldr	x19, [x0]
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	adrp	x1, _str86@page
	add	x1, x1, _str86@pageoff
	mov	x22, x0
	bl	_builder_lock_opt_str
	mov	x1, x0
	mov	x0, x22
	mov	x23, x1
	adrp	x1, _str88@page
	add	x1, x1, _str88@pageoff
	bl	_builder_lock_opt_str
	mov	x24, x0
	mov	x0, x19
	mov	x19, x0
	mov	x0, x23
	bl	_donna_string_is_empty
	mov	x17, x0
	mov	x0, x19
	mov	x19, x17
	mov	x22, x0
	mov	x0, x24
	bl	_donna_string_is_empty
	mov	x2, x24
	mov	x1, x23
	mov	x3, x0
	mov	x0, x22
	orr	x3, x19, x3
	mov	x4, #16
	sub	sp, sp, x4
	mov	x19, sp
	cmp	x3, #1
	beq	L26
	bl	_builder_lock_LockedDep
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x22, x0
	mov	x0, #24
	bl	_malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	_builder_lock_collect_locked
	str	x0, [x19]
	b	L30
L26:
	mov	x0, x21
	mov	x1, x20
	bl	_builder_lock_collect_locked
	str	x0, [x19]
	b	L30
L28:
	mov	x0, x20
	bl	_donna_list_reverse
L30:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	ldr	x24, [x29, 16]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
/* end function builder_lock_collect_locked */

.text
.balign 4
.globl _builder_lock_find_rev
_builder_lock_find_rev:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x21, x1
	mov	x1, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	L36
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x20, [x1]
	mov	x19, x0
	bl	_builder_lock_locked_name
	mov	x1, x21
	mov	x21, x1
	bl	_donna_string_equal
	mov	x1, x21
	mov	x2, x0
	mov	x0, x19
	mov	x3, #16
	sub	sp, sp, x3
	mov	x19, sp
	cmp	x2, #1
	beq	L35
	mov	x0, x20
	bl	_builder_lock_find_rev
	str	x0, [x19]
	b	L37
L35:
	bl	_builder_lock_locked_rev
	str	x0, [x19]
	b	L37
L36:
	adrp	x0, _str112@page
	add	x0, x0, _str112@pageoff
L37:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 48
	ret
/* end function builder_lock_find_rev */

.text
.balign 4
.globl _builder_lock_upsert
_builder_lock_upsert:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x2, _donna_nil@page
	add	x2, x2, _donna_nil@pageoff
	bl	_builder_lock_upsert_loop
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_upsert */

.text
.balign 4
_builder_lock_upsert_loop:
	hint	#34
	stp	x29, x30, [sp, -64]!
	mov	x29, sp
	str	x19, [x29, 56]
	str	x20, [x29, 48]
	str	x21, [x29, 40]
	str	x22, [x29, 32]
	str	x23, [x29, 24]
	ldr	x3, [x0]
	cmp	x3, #0
	beq	L45
	mov	x21, x2
	mov	x2, #8
	add	x2, x0, x2
	ldr	x22, [x2]
	mov	x19, x1
	mov	x1, #16
	add	x0, x0, x1
	ldr	x20, [x0]
	mov	x0, x22
	bl	_builder_lock_locked_name
	mov	x23, x0
	mov	x0, x19
	bl	_builder_lock_locked_name
	mov	x1, x0
	mov	x0, x23
	bl	_donna_string_equal
	mov	x1, x19
	mov	x23, x1
	mov	x1, #16
	sub	sp, sp, x1
	mov	x19, sp
	cmp	x0, #1
	beq	L43
	mov	x0, #24
	bl	_malloc
	mov	x1, x23
	mov	x2, x0
	mov	x0, #1
	str	x0, [x2]
	mov	x0, #8
	add	x0, x2, x0
	str	x22, [x0]
	mov	x0, #16
	add	x0, x2, x0
	str	x21, [x0]
	mov	x21, x1
	mov	x0, x20
	bl	_builder_lock_upsert_loop
	str	x0, [x19]
	b	L47
L43:
	mov	x2, x21
	mov	x21, x23
	mov	x0, x2
	bl	_donna_list_reverse
	mov	x22, x0
	mov	x0, #24
	bl	_malloc
	mov	x1, x0
	mov	x0, x22
	mov	x2, #1
	str	x2, [x1]
	mov	x2, #8
	add	x2, x1, x2
	str	x21, [x2]
	mov	x2, #16
	add	x2, x1, x2
	str	x20, [x2]
	bl	_donna_list_append
	str	x0, [x19]
	b	L47
L45:
	mov	x20, x2
	mov	x19, x1
	mov	x0, #24
	bl	_malloc
	mov	x2, x20
	mov	x1, x19
	mov	x3, #1
	str	x3, [x0]
	mov	x3, #8
	add	x3, x0, x3
	str	x1, [x3]
	mov	x1, #16
	add	x1, x0, x1
	str	x2, [x1]
	bl	_donna_list_reverse
L47:
	ldr	x19, [x29, 56]
	ldr	x20, [x29, 48]
	ldr	x21, [x29, 40]
	ldr	x22, [x29, 32]
	ldr	x23, [x29, 24]
	mov sp, x29
	ldp	x29, x30, [sp], 64
	ret
/* end function builder_lock_upsert_loop */

.text
.balign 4
.globl _builder_lock_write
_builder_lock_write:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x0
	mov	x0, x1
	bl	_builder_lock_format_lock
	mov	x1, x0
	mov	x0, x19
	bl	_donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
/* end function builder_lock_write */

.text
.balign 4
_builder_lock_format_lock:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	adrp	x1, _str165@page
	add	x1, x1, _str165@pageoff
	bl	_builder_lock_format_deps
	mov	x1, x0
	adrp	x0, _str164@page
	add	x0, x0, _str164@pageoff
	bl	___rt_str_concat
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_format_lock */

.text
.balign 4
_builder_lock_format_deps:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	str	x22, [x29, 16]
	mov	x17, x1
	mov	x1, x0
	mov	x0, x17
	mov	x20, x0
	ldr	x0, [x1]
	cmp	x0, #0
	beq	L54
	mov	x0, #8
	add	x0, x1, x0
	ldr	x0, [x0]
	mov	x2, #16
	add	x1, x1, x2
	ldr	x19, [x1]
	mov	x21, x0
	bl	_builder_lock_locked_name
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, _str178@page
	add	x0, x0, _str178@pageoff
	bl	___rt_str_concat
	adrp	x1, _str181@page
	add	x1, x1, _str181@pageoff
	bl	___rt_str_concat
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	mov	x22, x0
	bl	_builder_lock_locked_git
	mov	x1, x0
	mov	x0, x22
	mov	x22, x0
	adrp	x0, _str183@page
	add	x0, x0, _str183@pageoff
	bl	___rt_str_concat
	adrp	x1, _str186@page
	add	x1, x1, _str186@pageoff
	bl	___rt_str_concat
	mov	x17, x0
	mov	x0, x22
	mov	x22, x17
	bl	_builder_lock_locked_rev
	mov	x1, x0
	mov	x0, x21
	mov	x21, x0
	adrp	x0, _str188@page
	add	x0, x0, _str188@pageoff
	bl	___rt_str_concat
	mov	x1, x22
	mov	x22, x1
	adrp	x1, _str191@page
	add	x1, x1, _str191@pageoff
	bl	___rt_str_concat
	mov	x1, x22
	mov	x17, x0
	mov	x0, x21
	mov	x21, x17
	bl	___rt_str_concat
	mov	x1, x21
	bl	___rt_str_concat
	mov	x1, x0
	mov	x0, x20
	bl	___rt_str_concat
	mov	x1, x0
	mov	x0, x19
	bl	_builder_lock_format_deps
	b	L55
L54:
	mov	x0, x20
L55:
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldr	x22, [x29, 16]
	ldp	x29, x30, [sp], 48
	ret
/* end function builder_lock_format_deps */

.text
.balign 4
.globl _builder_lock_write_cached_rev
_builder_lock_write_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	mov	x19, x1
	adrp	x1, _str198@page
	add	x1, x1, _str198@pageoff
	bl	_donna_files_join
	mov	x1, x19
	bl	_donna_files_write
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
/* end function builder_lock_write_cached_rev */

.text
.balign 4
.globl _builder_lock_read_cached_rev
_builder_lock_read_cached_rev:
	hint	#34
	stp	x29, x30, [sp, -32]!
	mov	x29, sp
	str	x19, [x29, 24]
	adrp	x1, _str201@page
	add	x1, x1, _str201@pageoff
	bl	_donna_files_join
	mov	x19, x0
	bl	_donna_files_exists
	mov	x1, x0
	mov	x0, x19
	cmp	x1, #0
	beq	L60
	bl	_donna_files_read
	bl	_donna_string_trim
	b	L61
L60:
	adrp	x0, _str209@page
	add	x0, x0, _str209@pageoff
L61:
	ldr	x19, [x29, 24]
	ldp	x29, x30, [sp], 32
	ret
/* end function builder_lock_read_cached_rev */

.text
.balign 4
_builder_lock_opt_str:
	hint	#34
	stp	x29, x30, [sp, -16]!
	mov	x29, sp
	bl	_parsetoml_parsetoml_get_string
	ldr	x1, [x0]
	cmp	x1, #1
	beq	L64
	mov	x1, #8
	add	x0, x0, x1
	ldr	x0, [x0]
	b	L65
L64:
	adrp	x0, _str222@page
	add	x0, x0, _str222@pageoff
L65:
	ldp	x29, x30, [sp], 16
	ret
/* end function builder_lock_opt_str */

.text
.balign 4
___rt_str_concat:
	hint	#34
	stp	x29, x30, [sp, -48]!
	mov	x29, sp
	str	x19, [x29, 40]
	str	x20, [x29, 32]
	str	x21, [x29, 24]
	mov	x20, x1
	mov	x21, x0
	mov	x0, x21
	bl	_strlen
	mov	x19, x0
	mov	x0, x20
	bl	_strlen
	mov	x1, x21
	add	x0, x19, x0
	mov	x19, x1
	mov	x1, #1
	add	x0, x0, x1
	bl	_malloc
	mov	x1, x19
	mov	x19, x0
	bl	_strcpy
	mov	x1, x20
	mov	x0, x19
	mov	x19, x0
	bl	_strcat
	mov	x0, x19
	ldr	x19, [x29, 40]
	ldr	x20, [x29, 32]
	ldr	x21, [x29, 24]
	ldp	x29, x30, [sp], 48
	ret
/* end function __rt_str_concat */

