.data
.balign 8
donna_nil:
	.quad 0
/* end data */

.data
.balign 8
str46:
	.ascii "packages"
	.byte 0
/* end data */

.data
.balign 8
str86:
	.ascii "git"
	.byte 0
/* end data */

.data
.balign 8
str88:
	.ascii "rev"
	.byte 0
/* end data */

.data
.balign 8
str112:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str164:
	.ascii "# donna.lock "
	.byte 226
	.byte 128
	.byte 148
	.ascii " generated by donna build. Commit this file."
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str165:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str178:
	.ascii "[packages."
	.byte 0
/* end data */

.data
.balign 8
str181:
	.ascii "]"
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str183:
	.ascii "git = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str186:
	.byte 34
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str188:
	.ascii "rev = "
	.byte 34
	.byte 0
/* end data */

.data
.balign 8
str191:
	.byte 34
	.byte 10
	.byte 10
	.byte 0
/* end data */

.data
.balign 8
str198:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str201:
	.ascii ".donna_rev"
	.byte 0
/* end data */

.data
.balign 8
str209:
	.ascii ""
	.byte 0
/* end data */

.data
.balign 8
str222:
	.ascii ""
	.byte 0
/* end data */

.text
.balign 16
.globl builder_lock_LockedDep
builder_lock_LockedDep:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rdx, %r13
	movq %rsi, %r12
	movq %rdi, %rbx
	movl $32, %edi
	callq malloc
	movq %r13, %rdx
	movq %r12, %rsi
	movq %rbx, %rdi
	movq $0, (%rax)
	movq %rdi, 8(%rax)
	movq %rsi, 16(%rax)
	movq %rdx, 24(%rax)
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_LockedDep, @function
.size builder_lock_LockedDep, .-builder_lock_LockedDep
/* end function builder_lock_LockedDep */

.text
.balign 16
.globl builder_lock_locked_name
builder_lock_locked_name:
	endbr64
	movq 8(%rdi), %rax
	ret
.type builder_lock_locked_name, @function
.size builder_lock_locked_name, .-builder_lock_locked_name
/* end function builder_lock_locked_name */

.text
.balign 16
.globl builder_lock_locked_git
builder_lock_locked_git:
	endbr64
	movq 16(%rdi), %rax
	ret
.type builder_lock_locked_git, @function
.size builder_lock_locked_git, .-builder_lock_locked_git
/* end function builder_lock_locked_git */

.text
.balign 16
.globl builder_lock_locked_rev
builder_lock_locked_rev:
	endbr64
	movq 24(%rdi), %rax
	ret
.type builder_lock_locked_rev, @function
.size builder_lock_locked_rev, .-builder_lock_locked_rev
/* end function builder_lock_locked_rev */

.text
.balign 16
.globl builder_lock_read
builder_lock_read:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rdi, %rbx
	callq donna_files_exists
	movq %rbx, %rdi
	cmpq $0, %rax
	jz .Lbb18
	callq donna_files_read
	movq %rax, %rdi
	callq parsetoml_parsetoml_parse
	movq %rax, %rdi
	movq %rdi, %rbx
	callq parsetoml_parsetoml_is_err
	movq %rbx, %rdi
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz .Lbb17
	callq parsetoml_parsetoml_unwrap_table
	movq %rax, %rdi
	leaq str46(%rip), %rsi
	callq parsetoml_parsetoml_get_table
	subq $16, %rsp
	movq %rsp, %r12
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz .Lbb15
	movq 8(%rax), %rax
	subq $16, %rsp
	movq %rsp, %r13
	movq (%rax), %rcx
	cmpq $4, %rcx
	jz .Lbb13
	leaq donna_nil(%rip), %rax
	movq %rax, (%r13)
	leaq donna_nil(%rip), %rax
	jmp .Lbb14
.Lbb13:
	movq 8(%rax), %rdi
	leaq donna_nil(%rip), %rsi
	callq builder_lock_collect_locked
	movq %rax, (%r13)
.Lbb14:
	movq %rax, (%r12)
	jmp .Lbb16
.Lbb15:
	leaq donna_nil(%rip), %rax
	movq %rax, (%r12)
	leaq donna_nil(%rip), %rax
.Lbb16:
	movq %rax, (%rbx)
	jmp .Lbb19
.Lbb17:
	leaq donna_nil(%rip), %rax
	movq %rax, (%rbx)
	leaq donna_nil(%rip), %rax
	jmp .Lbb19
.Lbb18:
	leaq donna_nil(%rip), %rax
.Lbb19:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_read, @function
.size builder_lock_read, .-builder_lock_read
/* end function builder_lock_read */

.text
.balign 16
builder_lock_collect_locked:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $24, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rsi, %r12
	movq (%rdi), %rax
	cmpq $0, %rax
	jz .Lbb25
	movq 8(%rdi), %rax
	movq 16(%rdi), %rbx
	movq (%rax), %rdi
	movq %rdi, -16(%rbp)
	movq 8(%rax), %rdi
	leaq str86(%rip), %rsi
	movq %rdi, %r13
	callq builder_lock_opt_str
	movq %r13, %rdi
	movq %rax, %rsi
	movq %rsi, %r14
	leaq str88(%rip), %rsi
	callq builder_lock_opt_str
	movq %rbx, %rdi
	movq %rax, %r15
	movq %rdi, %rbx
	movq %r14, %rdi
	callq donna_string_is_empty
	movq %rbx, %rdi
	movq %rax, %rbx
	movq %rdi, %r13
	movq %r15, %rdi
	callq donna_string_is_empty
	movq %r15, %rdx
	movq %r14, %rsi
	movq %r13, %rdi
	movq %rdi, %r13
	movq -16(%rbp), %rdi
	orq %rbx, %rax
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz .Lbb23
	callq builder_lock_LockedDep
	movq %r13, %rdi
	movq %rax, %r13
	movq %rdi, %r14
	movl $24, %edi
	callq malloc
	movq %r14, %rdi
	movq %rax, %rsi
	movq $1, (%rsi)
	movq %r13, 8(%rsi)
	movq %r12, 16(%rsi)
	callq builder_lock_collect_locked
	movq %rax, (%rbx)
	jmp .Lbb27
.Lbb23:
	movq %r13, %rdi
	movq %r12, %rsi
	callq builder_lock_collect_locked
	movq %rax, (%rbx)
	jmp .Lbb27
.Lbb25:
	movq %r12, %rdi
	callq donna_list_reverse
.Lbb27:
	movq %rbp, %rsp
	subq $64, %rsp
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_collect_locked, @function
.size builder_lock_collect_locked, .-builder_lock_collect_locked
/* end function builder_lock_collect_locked */

.text
.balign 16
.globl builder_lock_find_rev
builder_lock_find_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rsi, %r13
	movq %rdi, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz .Lbb33
	movq 8(%rax), %rdi
	movq 16(%rax), %r12
	movq %rdi, %rbx
	callq builder_lock_locked_name
	movq %r13, %rsi
	movq %rax, %rdi
	movq %rsi, %r13
	callq donna_string_equal
	movq %r13, %rsi
	movq %rbx, %rdi
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz .Lbb32
	movq %r12, %rdi
	callq builder_lock_find_rev
	movq %rax, (%rbx)
	jmp .Lbb34
.Lbb32:
	callq builder_lock_locked_rev
	movq %rax, (%rbx)
	jmp .Lbb34
.Lbb33:
	leaq str112(%rip), %rax
.Lbb34:
	movq %rbp, %rsp
	subq $32, %rsp
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_find_rev, @function
.size builder_lock_find_rev, .-builder_lock_find_rev
/* end function builder_lock_find_rev */

.text
.balign 16
.globl builder_lock_upsert
builder_lock_upsert:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	leaq donna_nil(%rip), %rdx
	callq builder_lock_upsert_loop
	leave
	ret
.type builder_lock_upsert, @function
.size builder_lock_upsert, .-builder_lock_upsert
/* end function builder_lock_upsert */

.text
.balign 16
builder_lock_upsert_loop:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rdx, %r13
	movq %rsi, %r15
	movq (%rdi), %rax
	cmpq $0, %rax
	jz .Lbb42
	movq 8(%rdi), %r14
	movq 16(%rdi), %r12
	movq %r14, %rdi
	callq builder_lock_locked_name
	movq %rax, %rdi
	movq %rdi, %rbx
	movq %r15, %rdi
	callq builder_lock_locked_name
	movq %rbx, %rdi
	movq %rax, %rsi
	callq donna_string_equal
	subq $16, %rsp
	movq %rsp, %rbx
	cmpq $1, %rax
	jz .Lbb40
	movl $24, %edi
	callq malloc
	movq %r15, %rsi
	movq %rax, %rdx
	movq $1, (%rdx)
	movq %r14, 8(%rdx)
	movq %r13, 16(%rdx)
	movq %rsi, %r13
	movq %r12, %rdi
	callq builder_lock_upsert_loop
	movq %rax, (%rbx)
	jmp .Lbb44
.Lbb40:
	movq %r13, %rdx
	movq %r15, %r13
	movq %rdx, %rdi
	callq donna_list_reverse
	movq %rax, %rdi
	movq %rdi, %r14
	movl $24, %edi
	callq malloc
	movq %r14, %rdi
	movq %rax, %rsi
	movq $1, (%rsi)
	movq %r13, 8(%rsi)
	movq %r12, 16(%rsi)
	callq donna_list_append
	movq %rax, (%rbx)
	jmp .Lbb44
.Lbb42:
	movq %r13, %r12
	movq %r15, %rbx
	movl $24, %edi
	callq malloc
	movq %r12, %rdx
	movq %rbx, %rsi
	movq %rax, %rdi
	movq $1, (%rdi)
	movq %rsi, 8(%rdi)
	movq %rdx, 16(%rdi)
	callq donna_list_reverse
.Lbb44:
	movq %rbp, %rsp
	subq $48, %rsp
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_upsert_loop, @function
.size builder_lock_upsert_loop, .-builder_lock_upsert_loop
/* end function builder_lock_upsert_loop */

.text
.balign 16
.globl builder_lock_write
builder_lock_write:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	movq %rdi, %rbx
	movq %rsi, %rdi
	callq builder_lock_format_lock
	movq %rbx, %rdi
	movq %rax, %rsi
	callq donna_files_write
	popq %rbx
	leave
	ret
.type builder_lock_write, @function
.size builder_lock_write, .-builder_lock_write
/* end function builder_lock_write */

.text
.balign 16
builder_lock_format_lock:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	leaq str165(%rip), %rsi
	callq builder_lock_format_deps
	movq %rax, %rsi
	leaq str164(%rip), %rdi
	callq __rt_str_concat
	leave
	ret
.type builder_lock_format_lock, @function
.size builder_lock_format_lock, .-builder_lock_format_lock
/* end function builder_lock_format_lock */

.text
.balign 16
builder_lock_format_deps:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	pushq %rbx
	pushq %r12
	pushq %r13
	pushq %r14
	movq %rsi, %rbx
	movq %rdi, %rax
	movq (%rax), %rcx
	cmpq $0, %rcx
	jz .Lbb51
	movq 8(%rax), %rdi
	movq 16(%rax), %r12
	movq %rdi, %r13
	callq builder_lock_locked_name
	movq %r13, %rdi
	movq %rax, %rsi
	movq %rdi, %r13
	leaq str178(%rip), %rdi
	callq __rt_str_concat
	movq %rax, %rdi
	leaq str181(%rip), %rsi
	callq __rt_str_concat
	movq %r13, %rdi
	movq %rax, %r13
	movq %rdi, %r14
	callq builder_lock_locked_git
	movq %r14, %rdi
	movq %rax, %rsi
	movq %rdi, %r14
	leaq str183(%rip), %rdi
	callq __rt_str_concat
	movq %rax, %rdi
	leaq str186(%rip), %rsi
	callq __rt_str_concat
	movq %r14, %rdi
	movq %rax, %r14
	callq builder_lock_locked_rev
	movq %r13, %rdi
	movq %rax, %rsi
	movq %rdi, %r13
	leaq str188(%rip), %rdi
	callq __rt_str_concat
	movq %r14, %rsi
	movq %rax, %rdi
	movq %rsi, %r14
	leaq str191(%rip), %rsi
	callq __rt_str_concat
	movq %r14, %rsi
	movq %r13, %rdi
	movq %rax, %r13
	callq __rt_str_concat
	movq %r13, %rsi
	movq %rax, %rdi
	callq __rt_str_concat
	movq %r12, %rdi
	movq %rax, %rsi
	movq %rbx, %rax
	movq %rdi, %rbx
	movq %rax, %rdi
	callq __rt_str_concat
	movq %rbx, %rdi
	movq %rax, %rsi
	callq builder_lock_format_deps
	jmp .Lbb52
.Lbb51:
	movq %rbx, %rax
.Lbb52:
	popq %r14
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type builder_lock_format_deps, @function
.size builder_lock_format_deps, .-builder_lock_format_deps
/* end function builder_lock_format_deps */

.text
.balign 16
.globl builder_lock_write_cached_rev
builder_lock_write_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	movq %rsi, %rbx
	leaq str198(%rip), %rsi
	callq donna_files_join
	movq %rbx, %rsi
	movq %rax, %rdi
	callq donna_files_write
	popq %rbx
	leave
	ret
.type builder_lock_write_cached_rev, @function
.size builder_lock_write_cached_rev, .-builder_lock_write_cached_rev
/* end function builder_lock_write_cached_rev */

.text
.balign 16
.globl builder_lock_read_cached_rev
builder_lock_read_cached_rev:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	leaq str201(%rip), %rsi
	callq donna_files_join
	movq %rax, %rdi
	movq %rdi, %rbx
	callq donna_files_exists
	movq %rbx, %rdi
	cmpq $0, %rax
	jz .Lbb57
	callq donna_files_read
	movq %rax, %rdi
	callq donna_string_trim
	jmp .Lbb58
.Lbb57:
	leaq str209(%rip), %rax
.Lbb58:
	popq %rbx
	leave
	ret
.type builder_lock_read_cached_rev, @function
.size builder_lock_read_cached_rev, .-builder_lock_read_cached_rev
/* end function builder_lock_read_cached_rev */

.text
.balign 16
builder_lock_opt_str:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	callq parsetoml_parsetoml_get_string
	movq (%rax), %rcx
	cmpq $1, %rcx
	jz .Lbb61
	movq 8(%rax), %rax
	jmp .Lbb62
.Lbb61:
	leaq str222(%rip), %rax
.Lbb62:
	leave
	ret
.type builder_lock_opt_str, @function
.size builder_lock_opt_str, .-builder_lock_opt_str
/* end function builder_lock_opt_str */

.text
.balign 16
__rt_str_concat:
	endbr64
	pushq %rbp
	movq %rsp, %rbp
	subq $8, %rsp
	pushq %rbx
	pushq %r12
	pushq %r13
	movq %rsi, %r12
	movq %rdi, %rbx
	movq %rbx, %rdi
	callq strlen
	movq %rax, %r13
	movq %r12, %rdi
	callq strlen
	addq %r13, %rax
	movq %rax, %rdi
	addq $1, %rdi
	callq malloc
	movq %rbx, %rsi
	movq %rax, %rbx
	movq %rbx, %rdi
	callq strcpy
	movq %r12, %rsi
	movq %rbx, %rdi
	callq strcat
	movq %rbx, %rax
	popq %r13
	popq %r12
	popq %rbx
	leave
	ret
.type __rt_str_concat, @function
.size __rt_str_concat, .-__rt_str_concat
/* end function __rt_str_concat */

.section .note.GNU-stack,"",@progbits
